services:

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    depends_on:
      - db
      - elasticsearch
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=http://localhost:5001/api
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    build:
      context: ./backend/db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: biometrics
    ports:
      - "5432:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=biometrics
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  esdata:
  redis_data:
